require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RailsController do

  # This should return the minimal set of attributes required to create a valid
  # Rail. As you add validations to Rail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "db" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all rails as @rails" do
      rail = Rail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rails).should eq([rail])
    end
  end

  describe "GET show" do
    it "assigns the requested rail as @rail" do
      rail = Rail.create! valid_attributes
      get :show, {:id => rail.to_param}, valid_session
      assigns(:rail).should eq(rail)
    end
  end

  describe "GET new" do
    it "assigns a new rail as @rail" do
      get :new, {}, valid_session
      assigns(:rail).should be_a_new(Rail)
    end
  end

  describe "GET edit" do
    it "assigns the requested rail as @rail" do
      rail = Rail.create! valid_attributes
      get :edit, {:id => rail.to_param}, valid_session
      assigns(:rail).should eq(rail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rail" do
        expect {
          post :create, {:rail => valid_attributes}, valid_session
        }.to change(Rail, :count).by(1)
      end

      it "assigns a newly created rail as @rail" do
        post :create, {:rail => valid_attributes}, valid_session
        assigns(:rail).should be_a(Rail)
        assigns(:rail).should be_persisted
      end

      it "redirects to the created rail" do
        post :create, {:rail => valid_attributes}, valid_session
        response.should redirect_to(Rail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rail as @rail" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rail.any_instance.stub(:save).and_return(false)
        post :create, {:rail => { "db" => "invalid value" }}, valid_session
        assigns(:rail).should be_a_new(Rail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rail.any_instance.stub(:save).and_return(false)
        post :create, {:rail => { "db" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rail" do
        rail = Rail.create! valid_attributes
        # Assuming there are no other rails in the database, this
        # specifies that the Rail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Rail.any_instance.should_receive(:update).with({ "db" => "MyString" })
        put :update, {:id => rail.to_param, :rail => { "db" => "MyString" }}, valid_session
      end

      it "assigns the requested rail as @rail" do
        rail = Rail.create! valid_attributes
        put :update, {:id => rail.to_param, :rail => valid_attributes}, valid_session
        assigns(:rail).should eq(rail)
      end

      it "redirects to the rail" do
        rail = Rail.create! valid_attributes
        put :update, {:id => rail.to_param, :rail => valid_attributes}, valid_session
        response.should redirect_to(rail)
      end
    end

    describe "with invalid params" do
      it "assigns the rail as @rail" do
        rail = Rail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rail.any_instance.stub(:save).and_return(false)
        put :update, {:id => rail.to_param, :rail => { "db" => "invalid value" }}, valid_session
        assigns(:rail).should eq(rail)
      end

      it "re-renders the 'edit' template" do
        rail = Rail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rail.any_instance.stub(:save).and_return(false)
        put :update, {:id => rail.to_param, :rail => { "db" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rail" do
      rail = Rail.create! valid_attributes
      expect {
        delete :destroy, {:id => rail.to_param}, valid_session
      }.to change(Rail, :count).by(-1)
    end

    it "redirects to the rails list" do
      rail = Rail.create! valid_attributes
      delete :destroy, {:id => rail.to_param}, valid_session
      response.should redirect_to(rails_url)
    end
  end

end
