name: Check the Front code
on:
  push
jobs:
  test:
    name: Check the Front code2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run format