name: CI

on:
  push

env:
  FILE_PATTERN: "./frontend/app/src/**/*.{ts,tsx,js,jsx}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 19.x
      - name: Run Prettier
        run: |
          npx prettier --write ${FILE_PATTERN}
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Apply Prettier Change

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      shell: bash
      run: |
        docker-compose build
        docker-compose run app rake db:create
      env:
        RAILS_ENV: test

    - name: Run RSpec
      shell: bash
      run:  |
        docker-compose run app bundle exec rspec
      env:
        RAILS_ENV: test
